# Copyright (c) Meta Platforms, Inc. and affiliates.

name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            python-version: '3.12.7'
          - os: ubuntu-latest
            python-version: '3.13.0-rc.3'
          - os: windows-latest
            python-version: '3.13.0-rc.3'
          - os: macos-latest
            python-version: '3.13.0-rc.3'
          - os: ubuntu-latest
            python-version: '3.14.0-alpha.0'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Setup MSVC
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install dependencies
        run: |
          pip install --upgrade setuptools wheel

      - name: Build
        run: |
          python setup.py

      - name: Install wheel
        run: |
          pip install build/dist/*.whl
        shell: bash
        working-directory: ${{github.workspace}}

      - name: Test
        run: |
          mkdir test_dir
          cd test_dir
          python -m ft_utils.tests.test_run_all
        working-directory: ${{github.workspace}}
